<a href="https://colab.research.google.com/github/ruslanbakin/Numpy/blob/main/np_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 Создать новый проект. Импортировать NumPy под именем np

import numpy as np
import random

In [ ]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [ ]:
#2 . Создать вектор размера N*10, заполненный нулями

N = 2
A = np.zeros(N * 10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#3 Создать вектор размера 10, заполненный числом N
B = np.full((10),N)
print(B)

[2 2 2 2 2 2 2 2 2 2]


In [ ]:
#4 Создать вектор со значениями от N*5 до N*10
B = np.arange(N*5,N*10)
print(B)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#5 Создать матрицу N*5xN*5, заполнить любыми числами (обязательноналичие нулей)
B = np.full((N*5,N*5), [1,2,0,3,4,5,7,0,3,0])
print(B)

[[1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]]


In [ ]:
#6 Найти индексы ненулевых элементов в матрице, созданной на прошломшаге
nonzero_indices = np.nonzero(B)
print("Исходная матрица:")
print(B)
print("Индексы ненулевых элементов:")
index_matrix = np.column_stack(nonzero_indices)
for row in index_matrix:
    print(row)

Исходная матрица:
[[1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]
 [1 2 0 3 4 5 7 0 3 0]]
Индексы ненулевых элементов:
[0 0]
[0 1]
[0 3]
[0 4]
[0 5]
[0 6]
[0 8]
[1 0]
[1 1]
[1 3]
[1 4]
[1 5]
[1 6]
[1 8]
[2 0]
[2 1]
[2 3]
[2 4]
[2 5]
[2 6]
[2 8]
[3 0]
[3 1]
[3 3]
[3 4]
[3 5]
[3 6]
[3 8]
[4 0]
[4 1]
[4 3]
[4 4]
[4 5]
[4 6]
[4 8]
[5 0]
[5 1]
[5 3]
[5 4]
[5 5]
[5 6]
[5 8]
[6 0]
[6 1]
[6 3]
[6 4]
[6 5]
[6 6]
[6 8]
[7 0]
[7 1]
[7 3]
[7 4]
[7 5]
[7 6]
[7 8]
[8 0]
[8 1]
[8 3]
[8 4]
[8 5]
[8 6]
[8 8]
[9 0]
[9 1]
[9 3]
[9 4]
[9 5]
[9 6]
[9 8]


In [ ]:
#7 Создать случайный вектор размера N*15 и найти среднее значение всех
элементов
B = np.random.randint(0, 10, size=N*15)
C = sum(B)/len(B)
print(B)
print("Среднее значение:")
print(C)

[8 4 7 9 2 4 8 0 5 6 3 8 8 7 7 6 2 4 1 6 5 4 9 8 0 9 1 5 4 9]
Среднее значение
5.3


In [ ]:
#8
N = 2
B = np.random.randint(10,size =(N*5,N*5,N*5))
index_20 = B.shape
index_20_3d = np.unravel_index(N*10,index_20)
print(index_20_3d)

(0, 2, 0)


In [ ]:
#9
N = 2
B = np.random.randint(10,size = (N*5,N*3))
C = np.random.randint(10,size = (N*3,N*5))
result_dot = np.dot(B, C)

result_at = B @ C

result_dot_1 = B.dot(C)

print("Результат, используя np.dot:")
print(result_dot)

print("\nРезультат, используя @:")
print(result_at)

print("\nРезультат, используя dot:")
print(result_dot_1)

Результат, используя np.dot:
[[170 122 129 128  80  89 173 102 100 151]
 [191 158 137 146 103 132 210  93 100 145]
 [158 108 100 156  83 128 187  69 133 135]
 [135 102  94 141  76 112 172 102 127 145]
 [189 145 131 171 106 148 214  78 150 145]
 [107  45  70  91  34  43 107  36  66  98]
 [152  98 107 113  69  82 142  45  93 104]
 [185 127 134 177  90 121 225 120 142 194]
 [153 122 111 156  88 126 201  84 129 146]
 [175 147 158 169 111 123 198  87 199 149]]

Результат, используя @:
[[170 122 129 128  80  89 173 102 100 151]
 [191 158 137 146 103 132 210  93 100 145]
 [158 108 100 156  83 128 187  69 133 135]
 [135 102  94 141  76 112 172 102 127 145]
 [189 145 131 171 106 148 214  78 150 145]
 [107  45  70  91  34  43 107  36  66  98]
 [152  98 107 113  69  82 142  45  93 104]
 [185 127 134 177  90 121 225 120 142 194]
 [153 122 111 156  88 126 201  84 129 146]
 [175 147 158 169 111 123 198  87 199 149]]

Результат, используя dot:
[[170 122 129 128  80  89 173 102 100 151]
 [191 158 137 

In [ ]:
#10
B = np.arange(N*5,N*10)
print(B)
C = np.sort(B)[::-1]
print(C)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


In [ ]:
#11
import numpy as np

def generate_arrays(size):
    array1 = np.random.randint(0, 10, size)
    array2 = np.random.randint(0, 10, size)
    return array1, array2

def check_arrays(array1, array2):
    return np.array_equal(array1, array2)

def manual_edit(array, index):
    try:
        new_value = int(input(f"Введите новое значение для элемента с индексом {index}: "))
        array[index] = new_value
        print("Массив после ручной правки:", array)
    except ValueError:
        print("Ошибка: Введите целое число.")


arr1, arr2 = generate_arrays(5)

print("Array 1:", arr1)
print("Array 2:", arr2)

if check_arrays(arr1, arr2):
    print("Массивы одинаковы.")
else:
    print("Массивы различны.")

index_to_edit = int(input("Введите индекс элемента для ручной правки: "))
manual_edit(arr1, index_to_edit)

if check_arrays(arr1, arr2):
    print("Массивы после ручной правки остаются одинаковыми.")
else:
    print("Массивы после ручной правки различны.")




Array 1: [0 7 8 8 3]
Array 2: [8 8 6 5 4]
Массивы различны.
Введите индекс элемента для ручной правки: 3
Введите новое значение для элемента с индексом 3: 89
Массив после ручной правки: [ 0  7  8 89  3]
Массивы после ручной правки различны.


In [ ]:
#12
N = 2
A = np.random.randint(0, 10, size=N*15)

sred = np.mean(A)

print(A)
print(f'Среднее значение составляет: {sred}')

max_index = np.argmax(A)
A[max_index] = 0

print(f'Max был {np.max(A)} теперь: 0')
print(A)

[2 7 2 5 0 2 2 4 7 2 6 4 8 7 9 2 3 9 6 4 4 0 5 0 1 7 8 0 6 7]
Среднее значение составляет: 4.3
Max был 9 теперь: 0
[2 7 2 5 0 2 2 4 7 2 6 4 8 7 0 2 3 9 6 4 4 0 5 0 1 7 8 0 6 7]


In [ ]:
#13
N = 2
A = np.random.randint(10, size = N * 15)
print(A)
index = (np.abs(A - N).argmin())
print(f'Ближайшие число из массива к значению {N} = {A[index]}')

[5 5 7 4 0 7 8 9 9 0 5 0 7 3 1 4 3 0 8 5 8 6 2 4 1 3 7 0 8 6]
Ближайшие число из массива к значению 2 = 2


In [ ]:
#14
mean = 0
std = 1
size = 10
gaussian_array = np.random.normal(mean, std, size)
print(gaussian_array)


[-0.42216768  1.2915401  -0.97213028 -2.36182601  1.73242037  1.7585969
 -3.25148064 -0.28347138 -0.32529791 -0.38373636]


In [ ]:
#15
def diagonal_elements_product(matrix1, matrix2):

    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Нельзя умножить матрицы с данными размерами")

    product_matrix = np.dot(matrix1, matrix2)

    diagonal_elements = np.diagonal(product_matrix)

    return diagonal_elements

matrix_a = np.array([[5, 2], [3, 6]])
matrix_b = np.array([[8, 6], [2, 1]])

result = diagonal_elements_product(matrix_a, matrix_b)
print("Диагональные элементы произведения матриц:")
print(result)

Диагональные элементы произведения матриц:
[44 24]


In [ ]:
#16
N = 2
B = np.random.randint(10,size=(N * 5,N * 5))

C = B.flatten()

most_common_value = np.bincount(C).argmax()
least_common_value = np.bincount(C).argmin()

most_common_value = np.bincount(C).argmax()
least_common_value = np.bincount(C).argmin()

print(f"Наиболее часто встречающееся значение: {most_common_value}")
print(f"Наименее часто встречающееся значение: {least_common_value}")

Наиболее часто встречающееся значение: 7
Наименее часто встречающееся значение: 2


In [ ]:
#17
N = 2
array = np.array([1, 8, 3, 7, 2, 5, 6, 4])


A = array[np.argpartition(-array, N)[:N]]

B = array[np.argpartition(array, N)[:N]]

print(f"Исходный массив: {array}")
print(f"{N} Наибольших значения: {A}")
print(f"{N} Наименьших значения: {B}")

Исходный массив: [1 8 3 7 2 5 6 4]
2 Наибольших значения: [8 7]
2 Наименьших значения: [1 2]


In [ ]:
# 18
import numpy as np

N = 2
A = np.random.randint(0, 2, size=(N, N*2))
print("Исходная матрица A:")
print(A)
row_zeros = np.sum(A == 0, axis=1)


col_zeros = np.sum(A == 0, axis=0)


result = np.zeros((N+1, N*2+1), dtype=int)


result[:N, :N*2] = A
result[:N, N*2] = row_zeros


result[N, :N*2] = col_zeros
result[N, N*2] = np.sum(col_zeros)
print("\nРезультат обработки:")
print(result)

Исходная матрица A:
[[1 0 1 1]
 [0 1 1 1]]

Результат обработки:
[[1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 0 0 2]]


In [ ]:
import numpy as np


arr = np.array([2, 7, 1, 9, 5, 6])

# Находим индекс максимального элемента
i = np.argmax(arr)

# Новое значение, на которое вы хотите заменить максимальный элемент
new_value = 10

# Заменяем максимальный элемент на новое значение
arr[i] = new_value

# Выводим результат
print("Массив после замены:", arr)

Массив после замены: [ 2  7  1 10  5  6]
